# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import generator_pb2 as generator__pb2


class GeneratorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Generate = channel.unary_unary(
        '/Generator/Generate',
        request_serializer=generator__pb2.Request.SerializeToString,
        response_deserializer=generator__pb2.Response.FromString,
        )


class GeneratorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Generate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GeneratorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Generate': grpc.unary_unary_rpc_method_handler(
          servicer.Generate,
          request_deserializer=generator__pb2.Request.FromString,
          response_serializer=generator__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Generator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
